/var/lib/slurm-llnl/slurmd/job00003/slurm_script: line 21: module: command not found

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


wandb: Currently logged in as: st7ma784 (PGNTeam). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/user/.netrc
{'save_freq': 50, 'test_freq': 3, 'weight_decay': 0.0, 'warmup': 0, 'momentum': 0.9, 'test_batch_size': 16, 'num_workers': 32, 'epochs': 8, 'learning_rate': 0.0001, 'batch_size': 96, 'precision': 32, 'train_eps': 0.00784313725490196, 'train_numsteps': 10, 'train_stepsize': 0.00784313725490196, 'test_eps': 0.00392156862745098, 'test_numsteps': 10, 'test_stepsize': 0.00392156862745098, 'earlystop': 1000, 'freeze_text': True, 'optimizer': 'sgd', 'labelType': 'Modimage', 'root': './data', 'dataset': 'coco', 'image_size': 224, 'attack_type': 'pgd', 'test_attack_type': 'pgd', 'seed': 0, 'model_dir': './save/models', 'output_dir': './results', 'filename': None, 'trial': 1, 'resume': None, 'evaluate': False, 'debug': False, 'model': 'clip', 'imagenet_root': './data', 'arch': 'vit_b32', 'method': 'null_patch', 'prompt_size': 30, 'add_prompt_size': 0, 'train_class_count': 90, 'last_num_ft': -1, 'noimginprop': False, 'num_trials': 0, 'name': 'TestRun', 'hpc_exp_number': None, 'trials': <bound method HyperOptArgumentParser.opt_trials of parser(prog='Launch.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=False)>, 'optimize_parallel': <bound method HyperOptArgumentParser.optimize_parallel of parser(prog='Launch.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=False)>, 'optimize_parallel_gpu': <bound method HyperOptArgumentParser.optimize_parallel_gpu of parser(prog='Launch.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=False)>, 'optimize_parallel_cpu': <bound method HyperOptArgumentParser.optimize_parallel_cpu of parser(prog='Launch.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=False)>, 'generate_trials': <bound method HyperOptArgumentParser.generate_trials of parser(prog='Launch.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=False)>, 'optimize_trials_parallel_gpu': <bound method HyperOptArgumentParser.optimize_trials_parallel_gpu of parser(prog='Launch.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=False)>}
Version is:  coco_Modimage_0.0001_96_0.00784313725490196_10_0.00784313725490196_0.00784313725490196_pgd_30_0_sgd_True
Traceback (most recent call last):
  File "/data/PGDTest/Launch.py", line 235, in <module>
    wandbtrain(hyperparams)
  File "/data/PGDTest/Launch.py", line 109, in wandbtrain
    train(config,dir,devices,accelerator,Dataset,logtool)
  File "/data/PGDTest/Launch.py", line 18, in train
    model=myLightningModule(**config)
  File "/data/PGDTest/models/trainPGD.py", line 112, in __init__
    self.insert_eval_model_hook=self.insert_visual_model
  File "/home/user/miniconda3/envs/open-ce/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'myLightningModule' object has no attribute 'insert_visual_model'
srun: error: localhost: task 0: Exited with exit code 1
